version: "3.9"

services:
  sample:
    container_name: laser-vote
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:80
    environment:
      - CHOKIDAR_USEPOLLING=true
